version: '3'

services:
  eureka:
        image: anapsix/alpine-java:8_jdk_unlimited
        ports:
          - '8761:8761'
        working_dir: /eureka-server
        volumes:
          - ./eureka-server:/eureka-server
        command: './gradlew bootRun'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
        image: anapsix/alpine-java:8_jdk_unlimited
        ports:
          - '8080:8080'
        working_dir: /api-gateway
        volumes:
          - ./api-gateway:/api-gateway
        depends_on:
          - eureka
        command: './gradlew bootRun'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev
  users-api:
        image: anapsix/alpine-java:8_jdk_unlimited
        ports:
          - '8081:8081'
        volumes:
          - ./users-api:/users-api
        depends_on:
          - postgresdev
        working_dir: /users-api
        command: './gradlew bootRun'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev
  admins-api:
          image: anapsix/alpine-java:8_jdk_unlimited
          ports:
            - '8082:8082'
          volumes:
            - ./admins-api:/admins-api
          depends_on:
            - postgresdev
          working_dir: /admins-api
          command: './gradlew bootRun'
          environment:
            - GRADLE_USER_HOME=cache
            - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
        image: postgres
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=pgdev
  nyc-search-ui:
         image: node
         ports:
          - "3000:3000"
         working_dir: /nyc-search-ui
         volumes:
          - ./nyc-search-ui:/nyc-search-ui
         command: 'npm start'
         depends_on:
           - users-api
           - postgresdev
           - flyway-migrator
         environment:
           - REACT_APP_HOST=http://localhost:8080
  flyway-migrator:
          image: gsengun/flyway-postgres
          volumes:
            - ./sql:/flyway/sql
          depends_on:
            - postgresdev
            - users-api
          command: postgresdev 5432 postgres password pgdev public