INSERT INTO USERS
	(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, GENDER, EMAIL, PHONE_NUMBER, BIRTHDAY)
VALUES
	('zjtisme', '123456', 'Tony', 'Zhang', 'Male', 'jintai@gmail.com', '224-123-4567', '1993-09-09');

INSERT INTO ADMINS
    (USER_NAME, PASSWORD)
VALUES
    ('admin', 'admin');