INSERT INTO USERS
	(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, GENDER, EMAIL, PHONE_NUMBER, BIRTHDAY)
VALUES
	('zjtisme', '$2a$10$EwjCte5aAsbRJWVT1OTEbudh5l8iysgu7f9tgSPo.e/gVBoKMEmk6', 'Tony', 'Zhang', 'Male', 'jintai@gmail.com', '224-123-4567', '1993-09-09');

INSERT INTO ADMINS
    (USER_NAME, PASSWORD)
VALUES
    ('admin', '$2a$10$jImMUmf42GOR4RsqQMlONOjUoiDWtoWyeJBsfaIP6oacLE16fTnMa');